### ISSUE TITLE
希望有正则白名单可以对百度api进行拦截(因为百度审核的白名单不满足正则匹配和模糊匹配。且每次添加具有限制)

### ISSUE THREAD

**Issue by damemod** [cssxsh/mirai-administrator#11]
假如我想开启百度审核api的防广告功能，可防广告功能太过严格，如( www.baidu.com 都会被其所拦截)，我可以解决 www.baidu.com 的白名单问题，但解决不了由 www.baidu.com 衍生的所有相关链接的拦截。这可能得让我把百度云审核塞爆()。当然好的办法是关闭防广告功能，但一定不是一个妙的方法.
除此之外，我还并没有想到其他的应用场景，如果作者大大有想法可以提一下，让我醍醐灌顶。
最后特别感谢作者认真看完

**Comment by cssxsh** [comment]
你可以配置审核规则，调整审核敏感度

**Comment by damemod** [comment]
我进行尝试了一下，调节确实可以减少审核的严格性，但敏感度评级的标准有点难掌控,并且链接所在的评级是1，就是说想关闭对链接的检测除了通过白名单，就是关闭广告审查了

**Comment by damemod** [comment]
感谢作者，如果暂时没这方面计划的话，先close了，另外我发现我的叙述可能产生了错误，我发现审核的白名单是可以模糊匹配的，只是无法如正则这么灵活，感谢作者接受我提的垃圾issue，幸苦辣

**Comment by damemod** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
