### ISSUE TITLE
希望加一个针对不同用户使用不同help的功能

### ISSUE THREAD

**Issue by aipiao-gh** [cssxsh/mirai-administrator#12]
希望增加一个权限节点,然后对有这个节点的用户使用Mirai原版的help,对没有这个权限的人使用help只显示他有的权限所对应的指令

**Comment by cssxsh** [comment]
你的需求似乎原生 mirai 就已经达成，而且这也不是我这个插件该做的改动

另外，我的插件提供的 `reg` 指令, 通过转发消息构建内容，可以作为 `help` 的代替品
