### ISSUE TITLE
/contact black 时 消息过多导致无法发送

### ISSUE THREAD

**Issue by fffzzl** [cssxsh/mirai-administrator#17]
使用/contact black时后台Group(6674xxxx) <- --- Bot 小 茶 茶ʕ •ᴥ•ʔ(1220xxxxx) ---显示了1w多字，电脑端无显示，手机端显示 标题 点击查看完整内容（无法打开），可否做个消息分段，默认最新多少条，通过指令查看第二 三 页

**Comment by cssxsh** [comment]
要搞的话很多指令都得重新设计
我没啥时间
随缘吧
