### ISSUE TITLE
group相关指令在群聊内执行时将本群设为默认参数

### ISSUE THREAD

**Issue by Haocen2004** [cssxsh/mirai-administrator#18]
比如 /group quiet
将群号参数移至指令末尾 并在缺省时默认为当前群

**Comment by cssxsh** [comment]
这需要改大量的指令设计

**Comment by cssxsh** [comment]
https://github.com/mamoe/mirai/blob/dev/docs/ConsoleTerminal.md#群

你可以使用 `~` 直接代之当前群
