### ISSUE TITLE
邮件发送和上线通知问题

### ISSUE THREAD

**Issue by Speechless22** [cssxsh/mirai-administrator#20]
1.用Gmail账号和应用专用密码，超时报错
2.上线通知似乎无法触发

邮件发送失败, cause: Couldn't connect to host, port: smtp.gmail.com, 25; timeout -1

**Comment by cssxsh** [comment]
？

**Comment by Speechless22** [comment]
![image](https://user-images.githubusercontent.com/61347609/220012093-b20efd20-8bb9-4de7-9fbe-fd82a86f0583.png)
这里我按Gmail填的，/send log {addresses}提示超时

**Comment by cssxsh** [comment]
你确定你能直链 `smtp.gmail.com` ?

**Comment by Speechless22** [comment]
日本服务器，是不是要放行防火墙？

**Comment by cssxsh** [comment]
请先进行 ping 测试
请提供完整的日志
日志文件在 logs 文件夹

**Comment by cssxsh** [comment]
根据谷歌的文档，你需要指定端口
https://support.google.com/mail/?p=BadCredentials
```
# smtp
mail.smtp.starttls.enable=true
mail.smtp.starttls.required=true
mail.smtp.auth=true
mail.smtp.timeout=15000
mail.smtp.port=587
```

**Comment by Speechless22** [comment]
> 根据谷歌的文档，你需要指定端口 https://support.google.com/mail/?p=BadCredentials
> 
> ```
> # smtp
> mail.smtp.starttls.enable=true
> mail.smtp.starttls.required=true
> mail.smtp.auth=true
> mail.smtp.timeout=15000
> mail.smtp.port=587
> ```

解决了，谢谢
