### ISSUE TITLE
是否处理好友或者加群申请

### ISSUE THREAD

**Issue by YangXiaoguozi** [cssxsh/mirai-administrator#24]
可以增加一个控制加群申请和好友申请的配置嘛
 - 是否处理好友或者加群申请：默认true
 -- 是否处理好友申请：默认true
 -- 是否处理加群申请：默认true

**Comment by cssxsh** [comment]
你们总喜欢用奇怪的描述

**Comment by cssxsh** [comment]
https://github.com/cssxsh/mirai-administrator/actions/runs/5218022127
